version: '3.8'
services:
  newsletter-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./newsletter.db
    volumes:
      - ./newsletter.db:/app/newsletter.db
      - ./.env:/app/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000